### ISSUE TITLE
MDMultiChoose的回调无法确定哪些被选中了

### ISSUE THREAD

**Issue by flamezheng** [hss01248/DialogUtil#10]
StyledDialog.buildMdMultiChoose("请选择", names, checkedItems, new MyDialogListener() {
            @Override
            public void onFirst() {

            }

            @Override
            public void onSecond() {

            }
        }).show();
此回调方法无法确认，选中哪几项

**Comment by hss01248** [comment]
MyDialogListener是一个抽象类,不是接口,里面有一个回调方法onGetChoose(boolean[] states),是多选的回调
