### ISSUE TITLE
显示文字msg的建议

### ISSUE THREAD

**Issue by ParfoisMeng** [hss01248/DialogUtil#12]
StyledDialog.buildLoading("初始化...").show();有必要加个方法来动态的修改msg，比如我loading提示进度百分数。。

**Comment by hss01248** [comment]
恩,是少了一类:以圆形或线形或文字显示实时进度的progressdialog.后面加上

**Comment by ParfoisMeng** [comment]
不仅仅是进度的问题，最好是可以动态修改msg，比如我下载数据时显示正在下载的提示，下完后解压提示正在解压，解压后提示正在加载。。等等，大概就是这个意思。

**Comment by hss01248** [comment]
@ParfoisMeng 了解,已更新 StyledDialog.updateLoadingMsg(String msg)
