### ISSUE TITLE
报错  has leaked window com.android.internal.policy.PhoneWindow$DecorView

### ISSUE THREAD

**Issue by Jeromeer** [hss01248/DialogUtil#13]
作者您好,根据您的Demo,将setCurrentActivity放在base类中获取顶层activity,发现会出现has leaked window com.android.internal.policy.PhoneWindow$DecorView的bug,我debug跟踪了一下,发现是添加了activity引用之后,在窗体关闭之后,dialog还持有之前窗体的引用造成的,建议:可以添加针对activity的监听,生命周期同传入的activity;

**Comment by hss01248** [comment]
是loadingdialog?那个得用我提供的api来关闭,因为我这儿保持的是一个静态引用
