### ISSUE TITLE
现在在其他Activity界面调用的  Dialog 只显示在 第一层 Activity ，不会显示在当前调用的Activity 界面上。

### ISSUE THREAD

**Issue by flyjiang2014** [hss01248/DialogUtil#14]
现在在其他Activity界面调用的  Dialog 只显示在 第一层 Activity ，不会显示在当前调用的Activity 界面上。

比如 我从MainActivity(第一层 Activity) 跳转到  SecondActivity，然后再 SecondActivity执行  StyledDialog.buildLoading，结果SecondActivity没有弹出 Dialog，然后按返回键回到 MainActivity，发现Dialog显示在了MainActivit上。

请问是我哪里没设置好，还是bug 啊？

**Comment by flyjiang2014** [comment]
补充下，如果在 SecondActivity 加个点击按钮，点击后执行  StyledDialog.buildLoading ，就会在 SecondActivity弹出 Dialog了，但是如果直接 在  SecondActivity 的 onCreat 方法中直接  StyledDialog.buildLoading ，Dialog就会显示到上一个界面去了。这个怎么破。

现在的需求是 进入 Activity 后，在掉接口前 弹出加载loading,调完接口获取数据后 把 关闭弹窗，所以是要直接弹出 Dialog，

**Comment by hss01248** [comment]
这个啊,看来还得把指定context的功能加上.本来有,后来嫌每次都传太麻烦,就改成自动获取顶层activity了,但这个activity是onresume后才会被设置进去.你可以打个tag标记第一次onresume,在那里调用.我等下发个新版本,加上指定activity的功能
