### ISSUE TITLE
Dialog显示问题

### ISSUE THREAD

**Issue by Basakerone** [hss01248/DialogUtil#16]
StyledDialog.buildLoading().setActivity(mContext).show()或StyledDialog.buildLoading().show() 立即调用  StyledDialog.dismissLoading();取消不掉Dialog，使用情景是：初始化调用show();然后读取数据库的数据，有则加载数据，然后立即dismissLoading() 没有成功dismiss，否则加载网络数据在dismissLoading()。加载网络数据的回调中dismissLoading()能成功dismiss掉。

**Comment by hss01248** [comment]
是因为调用show后,真正show出来要两三百毫秒,这段时间内dialog.isshowing = false. 
bug已解决.内部维护一个show到dismiss的最短时间500ms.
