### ISSUE TITLE
onGetInput  输入框，怎么获取输入到的内容呢？

### ISSUE THREAD

**Issue by limjiregister** [hss01248/DialogUtil#23]
我设定一个全局变量，在onGetInput这个方法里面，赋值，然后，再在onSecond或者onFirst里获取这个变量，没法获取呢？null。而且，在onGetInput 里输出toast也获取不到输入内容。是我用的方式不对？跟你的例子一摸一样啊？？？

**Comment by hss01248** [comment]
onGetInput(CharSequence input1,CharSequence input2)  这个input1,intput2就是点击确定后拿到的你输入的值,不要去管onfirst方法了

**Comment by limjiregister** [comment]
哦哦，原来，我又设定了，两个按钮的文字，把“确定”放在右边了。所以一直获取不到，点击左边的就获取到了
