### ISSUE TITLE
如何判断当前页面是否有dialog正在显示？

### ISSUE THREAD

**Issue by ParfoisMeng** [hss01248/DialogUtil#29]
如题

**Comment by ParfoisMeng** [comment]
StyledDialog.isShowing();
类似这样的方法，建议增加一个

**Comment by hss01248** [comment]
每个show都会返回一个dialog啊,自己判断一下.

**Comment by ParfoisMeng** [comment]
我是说全局的。show返回的dialog只能在当前类中持有，无法全局判断，总不至于弄个全局量来持有吧。。。还有，传参的事件监听为啥不做空保护。。如果不做空保护也加个注解@NotNull啊。。inputdialog的edittext有可能要设置些东西呢，比如密文比如imeOptions等，所以考虑加个get方法会好点。。。
总的来说，DialogUtil还是挺不错的，但是不够开放，可定制化拓展性有点欠缺。能满足大部分需求，但一些业务上的需求很难实现，没有提供方法去自行拓展。
