### ISSUE TITLE
距离屏幕的左右边距能否自己设置

### ISSUE THREAD

**Issue by xuhuan** [hss01248/DialogUtil#3]
目前非底部的弹窗感觉离屏幕太近.

还有按钮有能看出来的淡灰色圆边框;
标题为null的时候能否隐藏掉标题部分,因为标题加粗了,不想要加粗的标题只能放到内容里,但标题为null目前依旧占位;

**Comment by hss01248** [comment]
这么多要求..自己拿源码去改改嘛

**Comment by hss01248** [comment]
@xuhuan 已修复相关问题
