### ISSUE TITLE
新电脑的新环境导入时的失败

### ISSUE THREAD

**Issue by xusheng927** [hss01248/DialogUtil#33]
compileSdkVersion 25
    buildToolsVersion '25.0.2'
        minSdkVersion 15
        targetSdkVersion 25

distributionUrl=https\://services.gradle.org/distributions/gradle-4.0-rc-1-all.zip
        classpath 'com.android.tools.build:gradle:3.0.0-alpha4'
Android Studio 3.0 Canary 4

导入项目的时候，DialogUtil:1.1.3 - DialogUtil:1.1.5都会定位到
    <style name="mystyle" parent="android:Animation">
    <item name="@android:windowEnterAnimation">@anim/dialog_enter</item>  //进入时的动画
    <item name="@android:windowExitAnimation">@anim/dialog_exit</item>    //退出时的动画

Messages提示
style attribute '@android:attr/windowEnterAnimation' not found
style attribute '@android:attr/windowExitAnimation' not found

Error:Execution failed for task ':app:processDebugResources'.
> Failed to execute aapt

**Comment by xusheng927** [comment]
已解决，gradle版本太高，应该是3.0.0多出了某些compile的新机制

//        classpath 'com.android.tools.build:gradle:3.0.0-alpha4'
改为
        classpath 'com.android.tools.build:gradle:2.3.0'

**Comment by hss01248** [comment]
恩,我也遇到了,用回as2.2就是好的,很多项目都这样.
