### ISSUE TITLE
底部弹出的dialog的实例图里的没有ios风格的啊

### ISSUE THREAD

**Issue by wudaotiantian** [hss01248/DialogUtil#34]
https://github.com/hss01248/DialogUtil/blob/master/imgs/ios_bottom.jpg

**Comment by hss01248** [comment]
buildBottomItemDialog

**Comment by wudaotiantian** [comment]
你这个是居中的啊。并不是挂在底部啊

**Comment by hss01248** [comment]
见 #35

**Comment by wudaotiantian** [comment]
我发现底部的取消的点击的效果，你是去掉了，还是没考虑过
