### ISSUE TITLE
小米5S 使用菊花框 不显示。

### ISSUE THREAD

**Issue by tanhaoshi** [hss01248/DialogUtil#38]
我用魅族，华为，三星手机都测试过了都能显示，为什么小米5s不能显示菊花框！

**Comment by DanteAndroid** [comment]
因为对小米来说，菊花太淫荡了。

**Comment by senjoeson** [comment]
小米NOTE无法显示,如果不能做到适配,估计你这个项目会被取缔!!!!

**Comment by hss01248** [comment]
被取缔?好怕怕...
手动setActivity一下,就可以了.貌似少部分国产机registerActivityLifecycleCallbacks不起作用.

**Comment by senjoeson** [comment]
怪我，我之前确实无法显示，后来发现是我的原因，抱歉哈😊加一个setActivity就好了。
