### ISSUE TITLE
使用菊花框  多个界面同时弹出，弹框叠加

### ISSUE THREAD

**Issue by whj920211** [hss01248/DialogUtil#41]
当一个页面通知其他几个页面同时刷新数据时，几个页面的弹框叠加，有时还会卡死，取消不掉，只能强制结束app

**Comment by hss01248** [comment]
1.指定activity:setActivity(xx)
2.任何框架都不是万能的,注意使用的场景:
2.1第一此进入页面,用layout内部的loadingview,有很多statelayout框架,也可以用我的这个:
https://github.com/hss01248/PageStateManager

2.2再次刷新,用刷新头显示刷新状态

2.3局部刷新或点击某按钮访问网络,用loading 对话框,不影响页面本身状态,类似web中的ajax请求.

本框架的loading dialog适用最后一种,不要滥用.
