### ISSUE TITLE
gradle3.0.0-beta4下不通过编译

### ISSUE THREAD

**Issue by Heleninsa** [hss01248/DialogUtil#45]
Error:(54, 5) style attribute '@android:attr/windowEnterAnimation' not found

**Comment by Sky-Walkrr** [comment]
@Heleninsa 原因是gradle plugin 3.0.0改变了aapt2的工作方式，已发PR给作者。详细信息可参考https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#aapt2

**Comment by hss01248** [comment]
已修复 @Heleninsa
