### ISSUE TITLE
请加多一个构造方法 如下图

### ISSUE THREAD

**Issue by meihuali** [hss01248/DialogUtil#46]
![qq 20170913211031](https://user-images.githubusercontent.com/23289782/30379095-f5ca31ba-98c7-11e7-9bda-6632d525e057.png)

代码如下：
    @Override
    public ConfigBean setBtnText(CharSequence positiveTxt) {
        return setBtnText(positiveTxt,"");
    }

另外就是把弹出的 对话框 稍微小一点吧·这里可以 当做 很多地方用例如 条件不满足的情况下就可以弹出来·提示 然后就只有一个确认按钮 爽多了·如果 弹出的框太大 ·就不好看了···或者暴露出一个 修改 边距 paiding 之类的 接口也可以

**Comment by meihuali** [comment]
本人Q  77299007

**Comment by hss01248** [comment]
近来在找工作,稍候...

**Comment by hss01248** [comment]
工作已找到,边距已可修改. 
另外说一句,很重要的,用第三方库一定要封装一层啊,不要直接用,api变了怎么办,你换一个库怎么办,你改动就大了

**Comment by hss01248** [comment]
ios风格的单一按钮似乎还没有实现,明天看看
