### ISSUE TITLE
又发现一个bug不显示菊花请看图

### ISSUE THREAD

**Issue by meihuali** [hss01248/DialogUtil#48]
![1111](https://user-images.githubusercontent.com/23289782/31608389-c6afea6a-b2a2-11e7-923a-a02ef53b62c8.png)

菊花弹不出来·debug 已经 打印 都走了·但是就显示不出来· 然而魅族 MX6 上又可以显示出来··· 还有就是我下面画红线的那个 dialog 是另外的一个·他就可以在别的机子上弹出来·

**Comment by hss01248** [comment]
@meihuali 有没有日志什么的?

**Comment by hss01248** [comment]
onActivityResult()发生在onResume()之前,这个loading 弹出在前一个界面的activity,前一个正在退出,为了防止crash,在内部捕捉了异常,所以你没看到对话框. 调一下setActivity吧
