### ISSUE TITLE
StyledDialog.buildIosAlert的按钮怎样自定义只有一个。

### ISSUE THREAD

**Issue by xusheng927** [hss01248/DialogUtil#5]
只需要确定的一个按钮。

**Comment by hss01248** [comment]
.setBtnText("sure","").show()

**Comment by hss01248** [comment]
发现会导致左下方没有圆角,,已更新:https://github.com/hss01248/DialogUtil/releases/tag/1.0.3

**Comment by xusheng927** [comment]
看了好久，原来左下角没有圆角，指的是按下效果没有圆角。
