### ISSUE TITLE
app_name

### ISSUE THREAD

**Issue by walorwang** [hss01248/DialogUtil#52]
<string name="app_name">对话框util</string>
导致工程gradle动态配置的app_name无效，请修复

**Comment by huangxunlei** [comment]
在res 中添加values-zh-rCN文件,将strings放进去

**Comment by ycads** [comment]
我也有这个问题，在productFlavors设置app_name会使用这个包的名称。

**Comment by hss01248** [comment]
已删除.
@huangxunlei 正解
