### ISSUE TITLE
引入了本库后，打混淆包异常

### ISSUE THREAD

**Issue by Rabtman** [hss01248/DialogUtil#54]
Warning: Exception while processing task java.io.IOException: proguard.ParseException: Expecting class member name before '@' in line 268 of file 
然后
FAILURE: Build failed with an exception.
去看了下268行，如下：
#Referenced at C:\Users\Evan-\.gradle\caches\transforms-1\files-1.1\DialogUtil-1.1.8.aar\75b9fcfcfc61534d465eed022a8304d4\res\layout\loading.xml:0
-keepclassmembers class * { *** @null(...); }   <-该语句为268行

混淆的配置文件加上，如下：
#DialogUtil
-dontwarn com.hss01248.dialog.**
-keep public class com.hss01248.dialog.* {*;}
依旧提示该错误
而去掉本库就可以正常打混淆后的包

AS版本 3.0
本库版本 1.1.8

**Comment by smarthityou** [comment]
我也是这个问题

**Comment by shuigesuntao** [comment]
一样

**Comment by shuigesuntao** [comment]
-keep @public class com.hss01248.dialog.* {*;}

**Comment by shuigesuntao** [comment]
一样

**Comment by hss01248** [comment]
-dontwarn com.hss01248.**
-keep class com.hss01248.** {*;}

**Comment by shuigesuntao** [comment]
加了
-dontwarn com.hss01248.**
-keep class com.hss01248.** {*;}

还是没有解决啊

# Referenced at /Users/suntao/.gradle/caches/transforms-1/files-1.1/DialogUtil-1.2.0.aar/d574942011f58b330902df356305e980/res/layout/loading.xml:0
-keepclassmembers class * { *** @null(...); }
