### ISSUE TITLE
【完善建议】建议添加设置全屏方法和宽度占满屏幕方法

### ISSUE THREAD

**Issue by feisher** [hss01248/DialogUtil#59]
在  ConfigBean类下添加
```
public ConfigBean setFillWith(boolean isFillWith){
        this.isFillWith = isFillWith;
        return this;
    }
```
然后  在Tool.java 类中的方法中加入判断
```
 if(istheTypeOfNotAdjust(bean.type)){
            if (bean.isFillWith) {
                wl.width = (int) (width * ratio);
            }
            /*wl.width = ViewGroup.LayoutParams.WRAP_CONTENT;
            wl.height = ViewGroup.LayoutParams.WRAP_CONTENT;*/
        }else {
……
```
**全屏同理，希望可以原生支持，这样就不用下拉代码修改了**

**Comment by hss01248** [comment]
参见:

setForceWidthPercent(@FloatRange(from = 0f,to = 1.0f)float forceWidthPercent)
setMaxWidthPercent(@FloatRange(from = 0f,to = 1.0f) float maxWidthPercent)
setForceHeightPercent(@FloatRange(from = 0f,to = 1.0f) float forceheightPercent)
setMaxHeightPercent(@FloatRange(from = 0f,to = 1.0f) float maxHeightPercent)
