### ISSUE TITLE
StyledDialog.buildMdSingleChoose

### ISSUE THREAD

**Issue by smarthityou** [hss01248/DialogUtil#9]
你好，请问怎么获取点击确定或者取消按钮的点击事件？

**Comment by hss01248** [comment]
MdSingleChoose 是用android原生的单选dialog实现的,虽然android本身可以设置确定或者取消按钮,但我这里封装的时候没有加,因为个人觉得,单选dialog,点击某一项,自然就是选那一项,那就是确定了,没必要再点击一次"确定",而取消的话,直接按后退键就好了

**Comment by smarthityou** [comment]
问题解决了   主要是当时你demo里面MdSingleChoose有 默认选中的位置   然后点击确认没有效果   我就来问你      现在我默认选中位置设置为-1   然后就没有选中了   这样就必须单选才行
